### ISSUE TITLE
Conversion from `LatLng` with +/-90 latitude to `CellID` results in incorrect `CellID` 

### ISSUE THREAD

**Issue by LafeWessel** [yjh0502/rust-s2#33]
When converting from a `LatLng` that has either 90.0 or -90.0 degree latitude to a `CellID`, the resulting `CellID` is incorrect. This is most obvious when immediately converting back to a `LatLng`. The result will have a slightly different latitude and a completely different longitude.

Here is an example test:
``` rust
#[test]
fn test(){
    let l1 = LatLng::from_degrees(90.0, 0.0);
    let c = CellID::from(l1);
    let l2 = LatLng::from(c);
    assert_eq!(l1, l2);
}
```

The output for this test is:
```
...
 left: `[90.0000000, 0.0000000]`,
right: `[89.9999999, -135.0000000]`
...
```

**Comment by yjh0502** [comment]
Here's equivalent Golang code snippet

```go
package main

import (
        "fmt"
        "github.com/golang/geo/s2"
)

func main() {
        ll0 := s2.LatLngFromDegrees(90.0, 0.0)
        ci := s2.CellIDFromLatLng(ll0)
        ll1 := ci.LatLng()
        fmt.Printf("ll0=%v\nci=%v\nll1=%v\n", ll0, ll1, ci)
}
```

output
```
ll0=[90.0000000, 0.0000000]
ci=[89.9999999, -135.0000000]
ll1=2/200000000000000000000000000000
```

A result is same with Golang library, so at least the implementation is on parity with Golang one.
I'll check how it works in c++.

**Comment by rconnorjohnstone** [comment]
In lat/lon space, a latitude of 90 degrees is a singularity point. 90 degrees latitude and 0 degrees longitude is the north pole. 90 degrees latitude and -135 degrees longitude is still the north pole.
