### ISSUE TITLE
Does not compile to wasm

### ISSUE THREAD

**Issue by That3Percent** [yjh0502/rust-s2#5]
I'm trying to use this library in WebAssembly, compiled via wasm-pack. It seems that it gets hung up on the float-extras crate with...
```
unresolved imports `libc::c_double`, `libc::c_int`                                                      
 --> github.com-1ecc6299db9ec823\float_extras-0.1.6\src\lib.rs:5:16
  |
5 |     use libc::{c_double, c_int};
  |                ^^^^^^^^  ^^^^^ no `c_int` in the root
  |                |
  |                no `c_double` in the root
```

Would it be possible to either not require this dependency, or to gate the functionality that uses this behind a feature flag so I can get some basic functionality like CellID?

**Comment by That3Percent** [comment]
Curiously, compiling from source does not have this problem since float-extras is not listed in Cargo.toml for the current version. So, I think all that would be needed to close this issue would be to package up and publish a new version.

**Comment by yjh0502** [comment]
Related https://github.com/yjh0502/float_extras/issues/1

**Comment by yjh0502** [comment]
`s2` `0.0.9` is just published, https://crates.io/crates/s2. Thanks for the report!

**Comment by That3Percent** [comment]
Works great! Thanks, and please accept this github star as a token of my appreciation.
